### ISSUE TITLE
Send "Flood" or "No Flood" from OpenMV to Boron

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/Boron#12]

**Comment by BentleySettin** [comment]
Here is the code in VSCode for the Boron ([d1e154](https://github.com/TinyCamML/Boron-and-OpenMV-Basics/commit/1d1e154b9737185783be5d1d862a0c3c1c278c90)) and OpenMV code (5c93b57). 

UART3 for the openMV camera was not sending information to the Boron. We switched to UART1 on the OpenMV camera and were able to have the Boron serial monitor read "Flood" or "No Flood". 

@ebgoldstein @anardek

**Comment by SUPScientist** [comment]
Confirming successful flood/no flood transmission from OpenMV to Boron. @BentleySettin, please include a wiring diagram for your successful setup also. I think this issue is safe to close.
