### ISSUE TITLE
Determine how to connect OpenMV to Boron

### ISSUE THREAD

**Issue by ebgoldstein** [TinyCamML/Boron#4]

**Comment by BentleySettin** [comment]
https://forums.openmv.io/t/communicate-between-multiple-openmvs-and-another-board/1538

**Comment by SUPScientist** [comment]
I think there are two decisions to be made, both of which seem to be under the umbrella of this issue.

1. Will the openMV send data to the Boron when the openMV decides it is ready to collect/transmit data? Or will the Boron wake up and request data from the openMV?
2. Will the openMV<—>Boron serial data transmission occur using UART, SPI, or I2C? @BentleySettin's link above describes UART, so that seems like a good starting point.

**Comment by BentleySettin** [comment]
As of now I will work on having the Boron wake up and request data from the openMV. I am emailing with Ryan now about recommendations he may have based on his work with the openMV camera. 

Yes, UART it is!

**Comment by SUPScientist** [comment]
@BentleySettin, add wiring diagram and photo of physical setup of Boron to OpenMV here or in a new subdirectory of this repo and link to it in a response to this issue thread.

**Comment by SUPScientist** [comment]
@BentleySettin, I am reopening this issue as I don't yet see a link to the circuit diagram which I consider to be a prerequisite to the completion of the issue. I don't mean that the diagram doesn't exist, just that I don't know where to find it. You can post it here and "close with comment" if/when you have that diagram.

**Comment by BentleySettin** [comment]
Here it is! [f054042](https://github.com/TinyCamML/Boron/commit/f054042dfd50384080abcc2cd84c333e2967ec9a)

I may leave this open or create a new issue that will have the full circuit diagram when we get closer to that stage.

**Comment by BentleySettin** [comment]
I will leave this issue to show connections between OpenMV and Boron (therefore close it) and use Boron-and-OpenMV-Basics issue #2 open for finalized circuit diagrams for all electronics and wires.

**Comment by SUPScientist** [comment]
Commented on the commit linked above (Here it is! [f054042](https://github.com/TinyCamML/Boron/commit/f054042dfd50384080abcc2cd84c333e2967ec9a)). Couple modifications needed. See comment in commit.
