### ISSUE TITLE
Investigate cloud endpoints for data

### ISSUE THREAD

**Issue by ebgoldstein** [TinyCamML/Boron#5]

**Comment by BentleySettin** [comment]
@ebgoldstein @anardek Do you guys have a desired end point for data from openMV? e.g. some server or other wesbite that you have set up? Alternitively we could set up a google sheet as a test case.

**Comment by ebgoldstein** [comment]
i vote for google sheet as a test case

**Comment by SUPScientist** [comment]
Sounds good. @BentleySettin, I have a "getting started" guide written up somewhere. It's well documented but...I don't remember where at the moment... I'll work with you on cellular data transmissions (please email me to coordinate a time) so set this aside for the moment.

**Comment by SUPScientist** [comment]
See here: https://github.com/UCSD-E4E/smartfin-fw-test/blob/main/integration.md.
Again, wait on activating cellular transmissions till we've coordinated. I need to "claim" your Boron to my account so that I retain access to it and don't lose the ability to work with it once you've graduated ;)

**Comment by SUPScientist** [comment]
Solved with https://github.com/TinyCamML/Boron-and-OpenMV/issues/3. Closing.
