### ISSUE TITLE
Send Bentley openMV code for tinyCamML

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/Boron#6]

**Comment by ebgoldstein** [comment]
For something very basic, look at these two scripts:
- This one detects if waves are hitting the dune in an image: 
https://github.com/UNCG-DAISY/TinyDuneCollision/blob/master/src/CollisionCam.py
- This one detects if there is a Moka (coffee) Pot in an image: 
https://github.com/ebgoldstein/MokaPotNet/blob/main/src/MokaPotNetCamOpenMV.py

They are both examples of what the OpenMV code will look like

**Comment by ebgoldstein** [comment]
I need to remake the real tinycamml openmv code, because it has lots of non-necessary code...

**Comment by BentleySettin** [comment]
Okay, thank you Evan! Dr. Anarde is dropping off an openMV cam tomorrow too.

**Comment by ebgoldstein** [comment]
@BentleySettin and @SUPScientist 
For TinyCamMLOpenMV code and model, please see here: https://github.com/TinyCamML/OMVmodel
