### ISSUE TITLE
Figure out Boron and openMV wire hook ups

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/Boron#7]
Strictly wiring. I created a **wiring diagram**

**Comment by SUPScientist** [comment]
Similar to https://github.com/TinyCamML/Boron/issues/4. Maybe one is meant to be more firmware-oriented and this issue is strictly wiring? Track https://github.com/TinyCamML/Boron/issues/4 with this one.

**Comment by BentleySettin** [comment]
I added a circuit diagram image. https://github.com/TinyCamML/Boron/commit/59c78a3dcd57f26668af5e1eef9ee4be4b3bcbb2

Is there a better way to display power to power connections? I was trying to find a symbol that represents power like the ground symbol in the circuit-diagram.org but could not find what I was looking for.

**Comment by SUPScientist** [comment]
That looks great. Thanks. I haven't carefully reviewed connections yet, but a couple comments and one answer. 

1. I recommend using different colors wherever possible. You have multiple black lines; changing colors on those would help someone trace connections more easily.
2. It looks like you are connecting one line to a pin labeled "NC" (which stands for "Not Connected") on the Boron. I imagine things should be changed to show Tx<—>Rx connections. NC by definition shouldn't have anything connected.
3. To your question, yes, it appears that you can add a power rail (which defaults to 5V), change to 3.3V, and add that connection everywhere you need 3.3V, as well as pull it off of the Boron which will essentially be its source. See screenshot below.
4. More on #3, I also recommend showing the battery input (and ground) to the Li+ pin on the Boron to complete your power circuits.

<img width="561" alt="image" src="https://github.com/TinyCamML/Boron/assets/7882374/bcfd130f-01e1-4de5-8079-483b8f13ab15">

**Comment by BentleySettin** [comment]
Got it! Thank you!
